### ISSUE TITLE
Add tests for GetFieldValue checking possibility of getting a stream or text reader

### ISSUE THREAD

**Issue by YohDeadfall** [mysql-net/AdoNetApiTest#144]
Originally posted by @roji in https://github.com/npgsql/npgsql/issues/2446#issue-434779986:

> [As mentioned by @Wraith2](https://github.com/dotnet/corefx/issues/35012#issuecomment-484462213), in SqlClient `DbDataReader.GetFieldValue<T>()` can be used to get a Stream or TextReader, exactly in the same way as currently returned by the dedicated `GetStream()` and `GetTextReader()` methods. We should implement this as well.
> 
> This has the advantage of also providing async column access via `GetFieldValueAsync()` without adding new `GetStreamAsync()` and `GetTextReaderAsync()`.

@bgrainger, assign this to me, please. I will take a care of it.

**Comment by bgrainger** [comment]
I added `GetFieldValueAsync` tests here: https://github.com/mysql-net/AdoNetApiTest/commit/04efd32e61a45a73cb0901385ddfe8ca7fa295d9
