### ISSUE TITLE
Test GetBytes with null buffer

### ISSUE THREAD

**Issue by bricelam** [mysql-net/AdoNetApiTest#8]
Another one of those *de facto* behaviors is that calling GetBytes with a null buffer will return the length of the data.

**Comment by bgrainger** [comment]
This should already be tested here: https://github.com/mysql-net/AdoNetApiTest/blob/ae131aa44fd281ad21bfc48448cbd7c7988d27c5/src/AdoNet.Specification.Tests/DataReaderTestBase.cs#L583-L587

**Comment by bricelam** [comment]
Doh, I searched for it too...
